### ISSUE TITLE
Adding `forge-gas-snapshot` natively in Foundry

### ISSUE THREAD

**Issue by zerosnacks** [marktoda/forge-gas-snapshot#11]
Hi @marktoda,

Thanks for this great library!

I'm interested in adding native cheatcodes in Foundry to make this functionality available out-of-the-box

I've created a first rough proposal of what I have in mind here: https://github.com/foundry-rs/foundry/issues/2056#issuecomment-2237053678

I would love to get your input on the requirements and the proposed API

**Comment by marktoda** [comment]
Ooh amazing!! I'll take a look thanks so much

**Comment by marktoda** [comment]
https://github.com/foundry-rs/foundry/pull/8952
